permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "frame-it studio"
  description:
    Frame-it is a company based on creativity, passion and quality that provides printing products for nursery rooms.
  font_url: "https://use.typekit.net/iha5xkn.css"
