permalink: pretty
theme: jekyll_patternbot
patternbot:
  title: "frame-it studio"
  description:
    Frame-it is a company based on creativity, passion and quality that provides printing products for nursery rooms.
  font_url: "https://use.typekit.net/iha5xkn.css"
  rationales:
    typefaces.primary: |
    Playfair Display Regular was chosen to be be used for all bodycopy because it is delicate as the site theme. In addition, it has high contrast features that ensure readability, even in small fonts.
    typefaces.secondary: |
    Josefin Sans Light is to be used for all highlighting text such as headings, buttons, lists, and also footer.
