title: "Banners"
description: |
  In order to direct the users' eyes to the artwork, the banners have white backgrounds.

patterns:
  call-to-action-banner:
    title: "call-to-action-banner"
    description: |
      There is only one Call-to-action banner at the homepage. There are two buttons on it.
